title: "dotNote"
email: januszpolowczyk19@gmail.com
description: "Software engineering, startups, and tech"
baseurl: "" # for GitHub Pages; if using custom domain adjust later
url: "https://januszpxyz.github.io"
lang: "en-US"
logo: "/assets/images/dotNoteLogo.png"
twitter_username: "januszpdev"
author:
  name: "Janusz Polowczyk Kilis"
# theme: jekyll-theme-persephone

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: erlzhang/jekyll-theme-persephone
# Optional / useful settings:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
sass:
  style: compressed
social:
  twitter: januszpdev
  github: JanuszPXYZ

show_header_title_on_scroll: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: "/assets/images/dotNetProfile.jpg"
# Persephone specific settings you may want to change:
# (look through the theme’s README for what’s configurable)
